# Generated by Django 5.2 on 2026-03-03 19:17

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INITIAL', 'Inventario Inicial'), ('PURCHASE', 'Compra'), ('PURCHASE_RETURN', 'Devolución de Compra'), ('SALE', 'Venta'), ('SALE_RETURN', 'Devolución de Venta'), ('ADJUSTMENT_IN', 'Ajuste de Entrada'), ('ADJUSTMENT_OUT', 'Ajuste de Salida'), ('TRANSFER_IN', 'Transferencia de Entrada'), ('TRANSFER_OUT', 'Transferencia de Salida')], max_length=15, verbose_name='tipo de movimiento')),
                ('naturality', models.CharField(choices=[('ENTRY', 'Entrada'), ('EXIT', 'Salida')], max_length=5, verbose_name='naturaleza')),
                ('quantity', models.PositiveIntegerField(verbose_name='cantidad')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='costo unitario')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('object_id', models.PositiveIntegerField()),
                ('observations', models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(10, 'Debe tener al menos 10 caracteres.')], verbose_name='observaciones')),
            ],
            options={
                'verbose_name': 'movimiento',
                'verbose_name_plural': 'movimientos',
                'db_table': 'movements',
            },
        ),
        migrations.CreateModel(
            name='HistoricalMovement',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('type', models.CharField(choices=[('INITIAL', 'Inventario Inicial'), ('PURCHASE', 'Compra'), ('PURCHASE_RETURN', 'Devolución de Compra'), ('SALE', 'Venta'), ('SALE_RETURN', 'Devolución de Venta'), ('ADJUSTMENT_IN', 'Ajuste de Entrada'), ('ADJUSTMENT_OUT', 'Ajuste de Salida'), ('TRANSFER_IN', 'Transferencia de Entrada'), ('TRANSFER_OUT', 'Transferencia de Salida')], max_length=15, verbose_name='tipo de movimiento')),
                ('naturality', models.CharField(choices=[('ENTRY', 'Entrada'), ('EXIT', 'Salida')], max_length=5, verbose_name='naturaleza')),
                ('quantity', models.PositiveIntegerField(verbose_name='cantidad')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='costo unitario')),
                ('date', models.DateTimeField(blank=True, editable=False, verbose_name='fecha')),
                ('object_id', models.PositiveIntegerField()),
                ('observations', models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(10, 'Debe tener al menos 10 caracteres.')], verbose_name='observaciones')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('content_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'historical movimiento',
                'verbose_name_plural': 'historical movimientos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
