# Generated by Django 5.2 on 2026-03-03 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0002_initial'),
        ('movements', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmovement',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmovement',
            name='product_unit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.productunit'),
        ),
        migrations.AddField(
            model_name='historicalmovement',
            name='tenant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='historicalmovement',
            name='warehouse',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='movement',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='movement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movement',
            name='product_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kardex', to='inventory.productunit'),
        ),
        migrations.AddField(
            model_name='movement',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.tenant'),
        ),
        migrations.AddField(
            model_name='movement',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.warehouse'),
        ),
        migrations.AddIndex(
            model_name='movement',
            index=models.Index(fields=['product_unit', 'warehouse'], name='movements_product_cee2f6_idx'),
        ),
        migrations.AddIndex(
            model_name='movement',
            index=models.Index(fields=['tenant', 'date'], name='movements_tenant__0b9e87_idx'),
        ),
        migrations.AddIndex(
            model_name='movement',
            index=models.Index(fields=['tenant', 'product_unit', 'warehouse'], name='movements_tenant__640b3a_idx'),
        ),
    ]
