# Generated by Django 5.2 on 2026-03-03 17:19

from django.db import migrations

SYSTEM_PERMISSIONS = [
    # usuarios
    ("users.view_profile", "Ver perfil"),
    ("users.update_profile", "Editar perfil"),
        
    # permisos
    ("permissions.view", "Ver permisos"),

    # bodegas
    ("warehouse.view", "Ver bodegas"),
    ("warehouse.history", "Ver historial de bodegas"),
    ("warehouse.create", "Crear bodegas"),
    ("warehouse.update", "Editar bodegas"),
    ("warehouse.delete", "Eliminar bodegas"),
    ("warehouse.activate", "Activar bodega"),
        
    # lista de precios
    ("list_price.view", "Ver lista de precios"),
    ("list_price.history", "Ver historial de lista de precios"),
    ("list_price.create", "Crear lista de precios"),
    ("list_price.update", "Editar lista de precios"),
    ("list_price.delete", "Eliminar lista de precios"),
    ("list_price.activate", "Activar lista de precios"),
    
    # categorias
    ("category.view", "Ver categorias"),
    ("category.history", "Ver historial de categoriaa"),
    ("category.create", "Crear categorias"),
    ("category.update", "Editar categorias"),
    ("category.delete", "Eliminar catgorias"),
    ("category.activate", "Activar categorias"),
        
    # productos
    ("product.view", "Ver productos"),
    ("product.kardex", "Ver historial"),
    ("product.create", "Crear productos"),
    ("product.update", "Editar productos"),
    ("product.delete", "Eliminar productos"),
    ("product.activate", "Activar productos"),
    ("product_unit.kardex", "Ver historial"),

        
    # producto unidad
    ("product_unit.view", "Ver unidad de productos"),
    ("product_unit.create", "Crear unidad de productos"),
    ("product_unit.update", "Editar unidad de productos"),
    ("product_unit.delete", "Eliminar unidad de productos"),
    ("product_unit.activate", "Activar unidad de productos"),
    ("product_unit.history", "Ver historial de unidad de productos"),
        
    #stock
    ("stock.view", "Ver inventario"),
        
    # movimientos
    ("movements.view", "Ver movimientos"),
    ("movements.create", "Crear movimientos"),
        
    # historial de precios
    ("price_history.view", "Ver historial de precios"),
    ("price_history.update", "Editar historial de precios"),
        
    # suscripciones
    ("suscriptions.view", "Ver suscripciones"),
        
    # dashboard
    ("dashboard.view", "Ver panel de administración"),
]


def seed_permissions(apps, schema_editor):
    Permission = apps.get_model("security", "Permission")
    
    for code, description in SYSTEM_PERMISSIONS:
        Permission.objects.update_or_create(
            code=code,
            defaults={"description": description}
        )
        
def reverse_seed_permissions(apps, schema_editor):
    Permission = apps.get_model("security", "Permission")
    codes = [code for code, _ in SYSTEM_PERMISSIONS]
    Permission.objects.filter(code__in=codes).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(seed_permissions, migrations.RunPython.noop),
    ]
