# Generated by Django 5.2 on 2026-03-03 19:17

import django.core.validators
import django.utils.timezone
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de edición')),
                ('name', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(3, 'Debe tener al menos 3 caracteres.')], verbose_name='nombre')),
                ('description', models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(10, 'Debe tener al menos 10 caracteres.')], verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCategory',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='estado')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='fecha de edición')),
                ('name', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(3, 'Debe tener al menos 3 caracteres.')], verbose_name='nombre')),
                ('description', models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(10, 'Debe tener al menos 10 caracteres.')], verbose_name='descripción')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical categoria',
                'verbose_name_plural': 'historical categorias',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalListPrice',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='estado')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='fecha de edición')),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('is_default', models.BooleanField(default=False, verbose_name='por defecto')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical lista de precio',
                'verbose_name_plural': 'historical lista de precios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPriceHistory',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='fecha de edición')),
                ('type_price', models.CharField(choices=[('SALE', 'Venta'), ('PURCHASE', 'compra')], max_length=8, verbose_name='tipo de precio')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio')),
                ('date_start', models.DateField(default=django.utils.timezone.now, verbose_name='fecha de inicio')),
                ('reason_change', models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(10, 'Debe tener al menos 10 caracteres.')], verbose_name='motivo de cambio')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='fecha de finalización')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical historial de precio de venta',
                'verbose_name_plural': 'historical historial de precios de venta',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='estado')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='fecha de edición')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descripcion')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical producto',
                'verbose_name_plural': 'historical productos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProductUnit',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='estado')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='fecha de edición')),
                ('presentation_name', models.CharField(max_length=150, verbose_name='nombre de presentación')),
                ('conversion_factor', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='factor de conversion')),
                ('is_base', models.BooleanField(default=False, verbose_name='medida base')),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('bar_code', models.CharField(blank=True, max_length=20, null=True)),
                ('plu', models.CharField(blank=True, max_length=6, null=True)),
                ('requires_weight', models.BooleanField(default=False, verbose_name='requiere peso')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Unidad de producto',
                'verbose_name_plural': 'historical Unidades de producto',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalStock',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='fecha de edición')),
                ('quantity', models.PositiveIntegerField(verbose_name='cantidad')),
                ('average_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='costo promedio')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Inventario',
                'verbose_name_plural': 'historical Inventarios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalWarehouse',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='estado')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='fecha de edición')),
                ('name', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(3, 'Debe tener al menos 3 caracteres.')], verbose_name='nombre')),
                ('location', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(3, 'Debe tener al menos 3 caracteres.')], verbose_name='ubicación')),
                ('observations', models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(10, 'Debe tener al menos 10 caracteres.')], verbose_name='observaciones')),
                ('is_default', models.BooleanField(default=False, verbose_name='por defecto')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical almacen',
                'verbose_name_plural': 'historical almacenes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ListPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de edición')),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('is_default', models.BooleanField(default=False, verbose_name='por defecto')),
            ],
            options={
                'verbose_name': 'lista de precio',
                'verbose_name_plural': 'lista de precios',
                'db_table': 'list_price',
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de edición')),
                ('type_price', models.CharField(choices=[('SALE', 'Venta'), ('PURCHASE', 'compra')], max_length=8, verbose_name='tipo de precio')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio')),
                ('date_start', models.DateField(default=django.utils.timezone.now, verbose_name='fecha de inicio')),
                ('reason_change', models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(10, 'Debe tener al menos 10 caracteres.')], verbose_name='motivo de cambio')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='fecha de finalización')),
            ],
            options={
                'verbose_name': 'historial de precio de venta',
                'verbose_name_plural': 'historial de precios de venta',
                'db_table': 'price_sales_history',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de edición')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descripcion')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de edición')),
                ('presentation_name', models.CharField(max_length=150, verbose_name='nombre de presentación')),
                ('conversion_factor', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='factor de conversion')),
                ('is_base', models.BooleanField(default=False, verbose_name='medida base')),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('bar_code', models.CharField(blank=True, max_length=20, null=True)),
                ('plu', models.CharField(blank=True, max_length=6, null=True)),
                ('requires_weight', models.BooleanField(default=False, verbose_name='requiere peso')),
            ],
            options={
                'verbose_name': 'Unidad de producto',
                'verbose_name_plural': 'Unidades de producto',
                'db_table': 'products_unit',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de edición')),
                ('quantity', models.PositiveIntegerField(verbose_name='cantidad')),
                ('average_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='costo promedio')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
            },
        ),
        migrations.CreateModel(
            name='UnitMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de edición')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('abbreviation', models.CharField(max_length=3, unique=True)),
            ],
            options={
                'verbose_name': 'unidad de medida',
                'verbose_name_plural': 'unidades de medida',
                'db_table': 'unit_measure',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de edición')),
                ('name', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(3, 'Debe tener al menos 3 caracteres.')], verbose_name='nombre')),
                ('location', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(3, 'Debe tener al menos 3 caracteres.')], verbose_name='ubicación')),
                ('observations', models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(10, 'Debe tener al menos 10 caracteres.')], verbose_name='observaciones')),
                ('is_default', models.BooleanField(default=False, verbose_name='por defecto')),
            ],
            options={
                'verbose_name': 'almacen',
                'verbose_name_plural': 'almacenes',
                'db_table': 'warehouse',
            },
        ),
    ]
