# Generated by Django 5.2 on 2026-03-03 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.tenant'),
        ),
        migrations.AddField(
            model_name='historicalcategory',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcategory',
            name='tenant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='historicallistprice',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicallistprice',
            name='tenant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='historicalpricehistory',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpricehistory',
            name='tenant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.category'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='tenant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='historicalproductunit',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalproductunit',
            name='tenant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='historicalstock',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalstock',
            name='tenant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='historicalwarehouse',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalwarehouse',
            name='tenant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='listprice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.tenant'),
        ),
        migrations.AddField(
            model_name='historicalpricehistory',
            name='list_price',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.listprice'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='list_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.listprice'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.tenant'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.tenant'),
        ),
        migrations.AddField(
            model_name='historicalproductunit',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='productunit',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units_measure', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='productunit',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.tenant'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='product_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_history', to='inventory.productunit'),
        ),
        migrations.AddField(
            model_name='historicalstock',
            name='product_unit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.productunit'),
        ),
        migrations.AddField(
            model_name='historicalpricehistory',
            name='product_unit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.productunit'),
        ),
        migrations.AddField(
            model_name='stock',
            name='product_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventory.productunit'),
        ),
        migrations.AddField(
            model_name='stock',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.tenant'),
        ),
        migrations.AddField(
            model_name='productunit',
            name='unit_measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.unitmeasure'),
        ),
        migrations.AddField(
            model_name='historicalproductunit',
            name='unit_measure',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.unitmeasure'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.tenant'),
        ),
        migrations.AddField(
            model_name='stock',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='historicalstock',
            name='warehouse',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.warehouse'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['tenant', 'created_at'], name='idx_category_tenant_created_at'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_category_name_tenant'),
        ),
        migrations.AddConstraint(
            model_name='listprice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('tenant',), name='unique_active_list_price_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='listprice',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_list_price_name_tenant'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_product_name_tenant'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['tenant', 'date_start'], name='price_sales_tenant__f9ecb4_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['tenant', 'date_end'], name='price_sales_tenant__cc0fe5_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['tenant', 'product_unit', 'list_price'], name='price_sales_tenant__f4cce1_idx'),
        ),
        migrations.AddConstraint(
            model_name='pricehistory',
            constraint=models.UniqueConstraint(fields=('tenant', 'product_unit', 'list_price'), name='unique_price_per_tenant_product_list'),
        ),
        migrations.AddConstraint(
            model_name='pricehistory',
            constraint=models.UniqueConstraint(condition=models.Q(('date_end__isnull', True)), fields=('product_unit', 'list_price', 'type_price'), name='unique_active_price_per_product_list_type'),
        ),
        migrations.AddConstraint(
            model_name='productunit',
            constraint=models.UniqueConstraint(condition=models.Q(('is_base', True)), fields=('tenant', 'product'), name='unique_base_unit_per_product_tenant'),
        ),
        migrations.AddConstraint(
            model_name='productunit',
            constraint=models.UniqueConstraint(condition=models.Q(('sku__isnull', False)), fields=('tenant', 'sku'), name='unique_product_unit_sku_tenant'),
        ),
        migrations.AddConstraint(
            model_name='productunit',
            constraint=models.UniqueConstraint(condition=models.Q(('bar_code__isnull', False)), fields=('tenant', 'bar_code'), name='unique_product_unit_bar_code_tenant'),
        ),
        migrations.AddConstraint(
            model_name='productunit',
            constraint=models.UniqueConstraint(condition=models.Q(('plu__isnull', False)), fields=('tenant', 'plu'), name='unique_product_unit_plu_tenant'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['tenant', 'created_at'], name='idx_wh_tenant_created'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('tenant',), name='unique_is_default_wh_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_warehouse_name_tenant'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['tenant', 'product_unit', 'warehouse'], name='inventory_s_tenant__256d6f_idx'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('tenant', 'product_unit', 'warehouse'), name='unique_stock_tenant_product_unit_warehouse'),
        ),
    ]
