# Generated by Django 5.2 on 2026-02-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_historicallistprice_listprice'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallistprice',
            name='is_base',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listprice',
            name='is_base',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='listprice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_base', True)), fields=('tenant',), name='unique_active_list_price_per_tenant'),
        ),
    ]
