# Generated by Django 5.2 on 2026-02-28 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_historicallistprice_is_base_listprice_is_base_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicallistprice',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical lista de precio', 'verbose_name_plural': 'historical lista de precios'},
        ),
        migrations.AlterModelOptions(
            name='listprice',
            options={'verbose_name': 'lista de precio', 'verbose_name_plural': 'lista de precios'},
        ),
        migrations.AlterModelTable(
            name='listprice',
            table='list_price',
        ),
    ]
