# Generated by Django 5.2 on 2026-02-28 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_historicallistprice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallistprice',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='listprice',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='nombre'),
        ),
    ]
