# Generated by Django 5.2 on 2026-02-28 19:24

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_historicallistprice_name_alter_listprice_name'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalWarehouse',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='estado activo')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='fecha de edición')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='nombre')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='ubicación')),
                ('observations', models.TextField(blank=True, null=True)),
                ('is_main', models.BooleanField(default=False, verbose_name='es principal')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical almacen',
                'verbose_name_plural': 'historical almacenes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='estado activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de edición')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='nombre')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='ubicación')),
                ('observations', models.TextField(blank=True, null=True)),
                ('is_main', models.BooleanField(default=False, verbose_name='es principal')),
            ],
            options={
                'verbose_name': 'almacen',
                'verbose_name_plural': 'almacenes',
                'db_table': 'warehouse',
            },
        ),
        migrations.RemoveConstraint(
            model_name='listprice',
            name='unique_active_list_price_per_tenant',
        ),
        migrations.RemoveField(
            model_name='historicallistprice',
            name='is_base',
        ),
        migrations.RemoveField(
            model_name='listprice',
            name='is_base',
        ),
        migrations.AddField(
            model_name='historicallistprice',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='es principal'),
        ),
        migrations.AddField(
            model_name='listprice',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='es principal'),
        ),
        migrations.AddConstraint(
            model_name='listprice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('tenant',), name='unique_active_list_price_per_tenant'),
        ),
        migrations.AddField(
            model_name='historicalwarehouse',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalwarehouse',
            name='tenant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tenant'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('tenant',), name='unique_active_warehouse_per_tenant'),
        ),
    ]
